manifest:
  defaults:
    remote: ruuvi

  remotes:
    - name: ruuvi
      url-base: https://github.com/ruuvi
    - name: ncs
      url-base: https://github.com/NordicPlayground
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
    - name: armmbed
      url-base: https://github.com/ARMmbed
    - name: civetweb
      url-base: https://github.com/civetweb
    
  projects:
    - name: zephyr
      repo-path: fw-nrfconnect-zephyr
      west-commands: scripts/west-commands.yml
      revision: 43f55fa7be2c86116af78e0a60486e5131b16ea1
    - name: ncs
      repo-path: fw-nrfconnect-nrf
      remote: ncs
      path: ruuvi/
      revision: v1.1.0
  
  self:
    path: ruuvi_node